env:
  ARCH: amd64

msvc_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  install_script:
    - choco install -y --no-progress cmake
    - choco install -y --no-progress visualstudio2019-workload-vctools
  build_script:
    - mkdir build && cd build
    - "\"%ProgramFiles%\\cmake\\bin\\cmake\" .."
    - "\"%ProgramFiles%\\cmake\\bin\\cmake\" --build ."
    - cd .. && mkdir build-shared && cd build-shared
    - "\"%ProgramFiles%\\cmake\\bin\\cmake\" -DBUILD_SHARED_LIBS=ON .."
    - "\"%ProgramFiles%\\cmake\\bin\\cmake\" --build ."
    - ./sample

linux_task:
  container:
    image: node:latest
  build_script:
    - apt update && apt install -y cmake
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - cd .. && mkdir build-shared && cd build-shared
    - cmake -DBUILD_SHARED_LIBS=ON ..
    - cmake --build .
    - ./sample

bsd_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  build_script:
    - pkg install --yes cmake
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - cd .. && mkdir build-shared && cd build-shared
    - cmake -DBUILD_SHARED_LIBS=ON ..
    - cmake --build .
    - ./sample

osx_task:
  osx_instance:
    image: mojave-xcode-10.2
  build_script:
    - brew install cmake
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
    - cd .. && mkdir build-shared && cd build-shared
    - cmake -DBUILD_SHARED_LIBS=ON ..
    - cmake --build .
    - ./sample
